services:
  chatgpt_reverse_proxy:
    image: ghcr.io/dreamhunter2333/chatgpt_reverse_proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt_reverse_proxy
    hostname: chatgpt-reverse-proxy
    restart: always
    ports:
      - "8000:8000"
      - "7900:7900"
    volumes:
      - ./tmp:/app/tmp
    environment:
      - VNC_NO_PASSWORD=1
      - user_data_dir=/app/tmp
      - auto_refersh_access_token=False
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8000/health_check || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
