name: Clean up docker images

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

jobs:
  clean-up-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: GHCR Delete Image for User
        uses: dreamhunter2333/ghcr-delete-image-action@v3
        with:
          owner: dreamhunter2333
          name: chatgpt_reverse_proxy
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 1

